name: Gerar e publicar site com Hugo

on:
  schedule:
    - cron: '0 3 * * *'  # Executa diariamente às 03:00 UTC
  workflow_dispatch:

jobs:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do repositório
        uses: actions/checkout@v3

      - name: Instalar Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.119.0'

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Instalar dependências Python
        run: pip install requests

      - name: Rodar script Python
        run: python atualizador_site.py

      - name: Gerar site com Hugo
        run: hugo

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
